### ISSUE TITLE
Update Container with Ontology: Metatype/Relationship Deletion Warning

### ISSUE THREAD

**Issue by jerenmb** [idaholab/Deep-Lynx#105]
## Reason

When a container is updated via an ontology file, the user should see a warning for any metatypes, metatype relationships, or relationships pairs that have associated node/edge data with them. This will avoid the unintentional removal of data associated with one of these container elements.

## Design

A container update via ontology import should remove these container elements if no data is associated with them. Otherwise the container update should fail and notify the user of the issue. This scenario could occur when a user deletes a class or relationship from an ontology and attempts to update an associated container in Deep Lynx.

## Impact

This enhancement affects the container update via import process as well as the associated GUI.

**Comment by DnOberon** [comment]
This should not be exclusive to the ontology update. Deletion from the main ontology management UI for metatypes, metatype relationships, and metatype relationship pairs should also have warnings.
