### ISSUE TITLE
Generating and Using API Keys instructions in wiki is outdated

### ISSUE THREAD

**Issue by brennanxyz** [idaholab/Deep-Lynx#107]
## Bug Description

The wiki page [Generating and Using API Keys](https://github.com/idaholab/Deep-Lynx/wiki/Generating-and-Using-API-Keys) states in the section **Using an API Key/Secret pair** that `oauth/token` is a POST request. It is now a GET.

## Impact
Misleading instructions for generating token

**Comment by DnOberon** [comment]
Corrected.
