### ISSUE TITLE
Setting up file storage

### ISSUE THREAD

**Issue by masonhorne** [idaholab/Deep-Lynx#171]
## Bug Description
When I was trying to set up file uploads I received an error about not having the correct directory due to not including in .env.  
Could you add information on how to get file storage working correctly to wiki getting started?

## Steps to Reproduce
Attempt to upload a file to a data source using the filesystem storage method without providing a path to the filesystem directory.

## Impact
An error appears in DeepLynx log and the post request is never received.

**Comment by DnOberon** [comment]
Added a section in Getting Started called "Installation Gotchas" explaining the errors when dealing with the filesystem.
