### ISSUE TITLE
API request "UploadFile" fails to automatically attach file to node.

### ISSUE THREAD

**Issue by alkuexan** [idaholab/Deep-Lynx#289]
## Bug Description
Hello Deep-Lynx Devs! I came across a potential bug with the Deep-Lynx processing system, and I was wondering if there was a simple fix to this issue. This has to do with the API request “UploadFile” in the Deep-Lynx API documentation in https://gitlab.software.inl.gov/b650/Deep-Lynx/-/blob/master/API%20Documentation/Core.swagger_collection.yaml.

The “UploadFile” description states that “Once Deep Lynx generates nodes and edges from that data, any files attached will automatically be attached to the resulting nodes/edges as well.” This request is able to upload both file and JSON metadata, but will not automatically attach the file to the new node in the graph tab.

Is there a simple solution to fix this issue? Let me know if you need any additional information!

## Steps to Reproduce
Using the Python requests library, I have uploaded a ZIP file and JSON metadata in one POST request, however, when the Deep-Lynx system processes the JSON data and creates the node, it fails to attach the ZIP file to the newly created node on the graph visualization tool. I have confirmed that the JSON metadata and the ZIP file are both within the Deep-Lynx database and can be downloaded using the “DownloadFile” request.

## Impact
We would like to see if we can use this to import data quickly using less requests and avoid too much internet traffic.

**Comment by DnOberon** [comment]
@alkuexan  Thank you for reporting this bug! We will look into it as soon as possible and get back to you if we cannot recreate it. Most likely it will be an easy fix :) 

Thank you for being a DeepLynx user!

**Comment by DnOberon** [comment]
Also @alkuexan could I ask you a little about what you're using DeepLynx for and where you're located? If you'd rather not share those, or not share those publicly you can email me at John.darrington@inl.gov. We are extremely interested in our outside users and want to make sure we're doing all we can to make your experience a good one!
