### ISSUE TITLE
Uploading files documentation doesn't seem to be correct

### ISSUE THREAD

**Issue by alahiff** [idaholab/Deep-Lynx#319]
## Bug Description

The URLs mentionedin https://github.com/idaholab/Deep-Lynx/wiki/Uploading-Files don't appear to be correct.

## Steps to Reproduce

Follow the documentation as described here: https://github.com/idaholab/Deep-Lynx/wiki/Uploading-Files using appropriate container and data source ids.

This gives an error:
```
Cannot POST /containers/1/datasources/1/files
```

[The documentation](https://github.com/idaholab/Deep-Lynx/wiki/Uploading-Files) refers to `/containers/:id/datasources/:id/files` but this does not appear to be listed on the [API documentation](https://github.com/idaholab/Deep-Lynx/blob/master/API%20Documentation/Core.swagger_collection.yaml). The API docs suggests that that `/containers/:id/import/datasources/:id/files` should be used, i.e. `import` in the path is missing.

I am using DeepLynx 1.5.1.

(As an aside I couldn't work out how to upload files & metadata successfully using `/containers/:id/import/datasources/:id/files` either but then came across the DeepLynx Python module and was able to use that).

**Comment by DnOberon** [comment]
@alahiff  Sorry you are running into some troubles. Did you get some help?
