### ISSUE TITLE
Timeseries File Retrofitting

### ISSUE THREAD

**Issue by DnOberon** [idaholab/Deep-Lynx#373]
## Reason

Get existing files to work with TS2

## Design

Button to retrofit existing files to be TS2 files:
- check if csv of json
- mark as timeseries
- adjust UUID position in filename in blob storage

## Impact

Doing backwards compatibility on demand avoids sweeping migrations and doesn't constrain us on TS2 design

**Comment by redoxeon** [comment]
see #479

**Comment by redoxeon** [comment]
#479 has been merged
