### ISSUE TITLE
API key "Notes" are missing

### ISSUE THREAD

**Issue by DnOberon** [idaholab/Deep-Lynx#384]
## Bug Description
The notes I've added to my API keys aren't coming through anymore, as of maybe the week of July 8

![image](https://media.github.inl.gov/user/15/files/5736f42b-42ec-4bc3-a56b-a92744c7ff20)

## Steps to Reproduce
Create an API key and add a note. The note is not visible

## Impact
Not sure which keys are orphaned/dangling/whatever

**Comment by browjm4** [comment]
will fix in new UI
