### ISSUE TITLE
Timeseries imports are not visible

### ISSUE THREAD

**Issue by DnOberon** [idaholab/Deep-Lynx#385]
## Bug Description
After uploading timeseries data to a timeseries data source, the import is not visible in the UX.

I know the team knows about this, just figured we should track it

![image](https://media.github.inl.gov/user/15/files/0339e81d-2ed2-4300-aca7-2f137826a86f)

## Steps to Reproduce
Design a timeseries table and upload data, before navigating to imports

## Impact
Generally low impact

**Comment by browjm4** [comment]
ts2/new UI will fix
