### ISSUE TITLE
UI Container Alerts refresh

### ISSUE THREAD

**Issue by DnOberon** [idaholab/Deep-Lynx#397]
## Bug Description

Certain container alert errors don't pop up right away if the error is caused by an async process such as a worker error.

## Steps to Reproduce

I encountered this error when importing a bad ontology. No errors in the UI upon upload, but if I refreshed the page the error would show. To solve this we would basically need to force a refresh of the page whenever a new container alert is created so it can be displayed as soon as the error occurs.

## Impact

UI change

**Comment by browjm4** [comment]
will be fixed in new UI
