### ISSUE TITLE
Container import failing on deeplynx.dev.inl.gov

### ISSUE THREAD

**Issue by jack-cavaluzzi** [idaholab/Deep-Lynx#472]
Import the attached container ontology and data sources on deeplynx.dev.inl.gov and you get a 500 response. The ontology imports successfully but the data sources do not. However, if you import this on deeplynx.de.inl.gov, you get a 200 response, and both the ontology and data sources import successfully.
[Container_Export.json](https://github.com/user-attachments/files/17168433/Container_Export.json)

**Comment by jack-cavaluzzi** [comment]
{
    "isError": true,
    "error": "{\"errorCode\":500,\"error\":\"[object Object] Tye mapping import is dependent on a successful data source import. Fix data source import errors to enable type mapping import.Container Import Result:\\nSuccessful ontology import. \\nType Mappings imported: 0\"}"
}

**Comment by browjm4** [comment]
Unable to reproduce locally. Added better error handling in an upcoming PR; if that's still not sufficient open a new issue and let me know so I can take another look :)
