### ISSUE TITLE
Graph query potentially pulling deleted nodes in connections

### ISSUE THREAD

**Issue by browjm4** [idaholab/Deep-Lynx#482]
## Bug Description

Deleted nodes are being included in graph queries

## Steps to Reproduce

Create a graph with a connecting node. Delete that node and see if you can write a depth of x query which should only return a single node, but instead may produce a connected graph

## Impact

Not ideal to be pulling deleted data from the graph

**Comment by redoxeon** [comment]
bugfix has been merged
