### ISSUE TITLE
"In" Operator Not Working in Type Mapping

### ISSUE THREAD

**Issue by peter-suyderhoud** [idaholab/Deep-Lynx#492]
## Bug Description

When type mapping, it appears as though the "in" operator is not searching for the values supplied in a list format.

## Steps to Reproduce

Please contact kevin.orear@inl.gov for a screenshare.

## Impact

Unable to type map incoming data for INL data sources

**Comment by era-zx** [comment]
validation now performed on non-root arrays and payload parsing was cleaned up
