### ISSUE TITLE
Deep-Lynx login failure

### ISSUE THREAD

**Issue by brennanxyz** [idaholab/Deep-Lynx#98]
## Bug Description
![err1](https://user-images.githubusercontent.com/53807547/104487042-d5284a00-5589-11eb-817b-82608149346c.png)
Error message on failed login is not parsed

## Steps to Reproduce
Attempt to log in to Deep Lynx with a username that doesn't exist in the database

## Impact
Low impact

**Comment by DnOberon** [comment]
Super descriptive error right? Most likely need will need to set a generic error stating they can't login with that Username/Password. Don't need to inform the user what kind of error it is, and definitely don't want to inform the user if an email address currently exists in the system.
